name: photo
channels:
    - default
    - conda-forge
dependencies:
    - python=3.10
    - scipy
    - numpy
    - pandas
    - cudatoolkit
    - torch
    - scikit-learn
    - scikit-image
    - opencv
    - pillow
    - matplotlib
    - jupyter
    - ipywidgets
    - jupyterlab
    - jupyter_contrib_nbextensions
    - jupyterlab-git


