name: numdev
channels:
    - default
    - conda-forge
dependencies:
    - python=3.10
    - pip
    - asyncpg
    - aiohttp
    - numpy
    - scipy
    - scikit-learn
    - statsmodels
    - matplotlib
    - pandas
    - seaborn
    - quarto
    - hatch
