name: spyder3-ide
channels:
    - default
    - conda-forge
dependencies:
    - python=3.8
    - scikit-learn==0.22
    - numpy
    - scipy
    - matplotlib
    - pandas
    - spyder>=3.0,<4.0
    - ipywidgets
    - xlrd
    - requests
    - dnspython
    - pymongo
    - arrow>=1.0
    - elasticsearch>=7.0.0,<8.0.0
    - psycopg2==2.8.6
    - tpot
    - pweave

