name: jupyter-base
channels:
    - default
    - conda-forge
includes:
    - conda-numdev.yml

dependencies:
    - pip
    - jupyter
    - ipywidgets
    - jupyterlab
    - jupyter_contrib_nbextensions
    - jupyterlab-git
    - seaborn

