name: cuda
channels:
    - default
    - conda-forge
dependencies:
    - python=3.8
    - requests
    - dnspython
    - asyncpg
    - aiohttp
    - cudatoolkit
    - scipy
    - scikit-learn
    - numpy
    - pandas
    - matplotlib
    - seaborn
    - torch
    - xgboost
    - tpot
    - jupyter
    - ipywidgets
    - jupyterlab
    - jupyter_contrib_nbextensions
    - jupyterlab-git

